restaurants:
  hosts:
    tokyo:
      ansible_host: 192.168.56.11
      ansible_user: tokyo

    yokohama:
      ansible_host: 192.168.56.12
      ansible_user: yokohama

    omiya:
      ansible_host: 192.168.56.13
      ansible_user: omiya
